[workspace]
members = [
    "graal",         # graphics resource abstraction layer
    "graal-macros",
]
resolver = "2"

[workspace.dependencies]
graal = { path = "graal" }
graal-macros = { path = "graal-macros" }

[profile.release]
debug = true
