[package]
name = "graal-spirv"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = '2018'

[dependencies]
byteorder = "1.4.3"
spirv_headers = "1.5.0"
ordered-float = "2.1.1"
num-traits = "0.2.14"

