[package]
name = "mlr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoffset = "0.9.0"
ordered-float = "4.1.1"
graal = { workspace = true }
mlr-macros = { workspace = true }